"""HK IR -> HipKittens C++.

The output is meant to be *read*. When a kernel spills or mis-schedules, the
generated .cpp is the artifact you take to /kernel-resource-check and to the
disassembler, and a generator whose output nobody can follow just moves the
debugging problem somewhere worse. So: real names, the IR op that produced each
line in a comment, and the same structure a hand-written kernel in
kernels/rdna3 has (globals struct, config, __global__, launch, pybind).

Values become named C++ locals and every op is emitted in destination-passing
form, which is what include/rdna3 exposes. The IR is in value form precisely so
that this step -- and only this step -- has to think about destinations.
"""

from __future__ import annotations

from typing import Dict, List, Sequence

from ..ir.nodes import (
    GlobalType,
    KernelIR,
    Op,
    RegTileType,
    RegVecType,
    SharedTileType,
    Value,
)
from ..lang.host import emit_dim
from ..lang.ops import (BINARY, BROADCASTS, FILLS, MMA, REDUCTIONS, SCALARS,
                        UNARY)
from ..target import get_target


class CodegenError(Exception):
    pass


class Emitter:
    def __init__(self, ir: KernelIR):
        self.ir = ir
        self.target = get_target(ir.arch)
        # Shared with ir.dump(), so the textual IR and the C++ name each value
        # identically.
        self.names: Dict[int, str] = ir.value_names()
        self.aliases: Dict[object, str] = {}
        self.lines: List[str] = []
        self.indent = 1
        self._opaque = 0

    # -- helpers -----------------------------------------------------------

    def w(self, line: str = "") -> None:
        self.lines.append(("    " * self.indent + line) if line else "")

    def name(self, v: Value) -> str:
        # A tensor is a member of the globals struct, not a local.
        if isinstance(v.type, GlobalType):
            return f"g.{v.name}"
        n = self.names.get(id(v))
        if n is None:
            raise CodegenError(
                f"value {v!r} ({v.type}) has no definition in this kernel. "
                f"It was most likely produced while tracing a different kernel."
            )
        return n

    # -- top level ---------------------------------------------------------

    def emit(self, includes: Sequence[str] = ('"kittens.cuh"',)) -> str:
        """Everything except the module scaffold: includes, globals, the
        __global__ itself and a host `launch`. What wraps it -- pybind, a torch
        library, nothing at all -- is codegen.scaffold's business."""
        self.lines = []
        self._header(includes)
        self._globals_struct()
        self._kernel()
        self._launch()
        return "\n".join(self.lines) + "\n"

    def _header(self, includes: Sequence[str]) -> None:
        ir = self.ir
        self.indent = 0
        self.w("// Generated by hk (HipKittens Python IR). Do not edit by hand;")
        self.w("// edit the kernel that produced it and regenerate.")
        self.w("//")
        self.w(f"// kernel : {ir.name}")
        self.w(f"// arch   : {ir.arch}  warps={ir.warps} threads={ir.threads}")
        if ir.consts:
            consts = ", ".join(f"{k}={v}" for k, v in sorted(ir.consts.items()))
            self.w(f"// const  : {consts}")
        self.w(f"// LDS    : {ir.lds_bytes} B")
        for wn in ir.warnings:
            for line in str(wn).splitlines():
                self.w(f"// WARN   : {line.strip()}")
        self.w()
        for inc in includes:
            self.w(f"#include {inc}")
        self.w()
        self.w("using namespace kittens;")
        self.w()

    def _globals_struct(self) -> None:
        ir = self.ir
        self.w("struct globals {")
        self.indent = 1
        for p in ir.tensors():
            self.w(f"{p.type.cpp()} {p.name};")
        self.w()
        self.w("dim3 grid() const {")
        self.indent = 2
        # `g` is the name the host expressions were built against.
        self.w("const globals &g = *this;")
        x, y, z = ir.grid
        self.w(f"return dim3({emit_dim(x)}, {emit_dim(y)}, {emit_dim(z)});")
        self.indent = 1
        self.w("}")
        self.w(f"dim3 block() const {{ return dim3({ir.threads}); }}")
        if ir.lds_bytes:
            self.w(f"size_t dynamic_shared_memory() const {{ return {ir.lds_bytes}; }}")
        self.indent = 0
        self.w("};")
        self.w()

    def _aliases(self) -> None:
        """One `using` per distinct tile or vector type.

        Spelled out, `kittens::rt<bf16, 16, 64, kittens::ducks::rt_layout::row>`
        is 55 characters that appear on nearly every line, and the attention
        kernel has six such types. Aliasing them is the difference between
        generated code you can diff against the hand-written kernel and
        generated code you skim past.

        Vectors get an alias too, and it is spelled in terms of the tile's --
        `rt_fp32_16x64_row::col_vec` -- because that is the only honest way to
        write it: an rv's lane layout is derived from the tile it came off, and
        a vector written independently of its tile is the bug this naming makes
        hard to commit.
        """
        seen = {}

        def note(ty) -> None:
            # `.plain`: a refinement the IR tracks (RegVecType.uniform) has no
            # C++ spelling, so the refined and the plain vector are one alias.
            ty = ty.plain
            if isinstance(ty, RegVecType):
                note(ty.tile)  # before the vector, so the `using` order works
            if isinstance(ty, (RegTileType, SharedTileType, RegVecType)):
                seen.setdefault(ty, self._alias_name(ty))

        for op in self.ir.walk():
            for v in list(op.results) + list(op.operands) + list(op.block_args):
                note(v.type)
        if not seen:
            return
        for ty, alias in seen.items():
            if isinstance(ty, RegVecType):
                self.w(f"using {alias} = {seen[ty.tile]}::{ty.kind}_vec;")
            else:
                self.w(f"using {alias} = {ty.cpp()};")
        self.w()
        self.aliases = {ty: alias for ty, alias in seen.items()}

    @staticmethod
    def _alias_name(ty) -> str:
        if isinstance(ty, RegTileType):
            return f"rt_{ty.dtype.name}_{ty.rows}x{ty.cols}_{ty.layout}"
        if isinstance(ty, RegVecType):
            t = ty.tile
            return f"rv_{t.dtype.name}_{t.rows}x{t.cols}_{t.layout}_{ty.kind}"
        return f"st_{ty.dtype.name}_{ty.rows}x{ty.cols}"

    def cpp(self, ty) -> str:
        """The name to write for a type: its alias when it has one."""
        return self.aliases.get(ty.plain, None) or ty.cpp()

    def _kernel(self) -> None:
        ir = self.ir
        self._aliases()
        self.w(f"__global__ __launch_bounds__({ir.threads}, 1)")
        self.w(f"void {ir.name}_kernel(const globals g) {{")
        self.indent = 1
        if ir.lds_bytes:
            self.w("extern __shared__ alignment_dummy __shm[];")
            self.w("shared_allocator al((int*)&__shm[0]);")
            self.w()
        for op in ir.body:
            self._op(op)
        self.indent = 0
        self.w("}")
        self.w()

    def _launch(self) -> None:
        ir = self.ir
        self.w("static void launch(const globals &g) {")
        self.indent = 1
        if ir.lds_bytes:
            self.w(
                f"hipFuncSetAttribute((void *)&{ir.name}_kernel, "
                f"hipFuncAttributeMaxDynamicSharedMemorySize, {ir.lds_bytes});"
            )
            self.w(f"{ir.name}_kernel<<<g.grid(), g.block(), {ir.lds_bytes}>>>(g);")
        else:
            self.w(f"{ir.name}_kernel<<<g.grid(), g.block()>>>(g);")
        self.indent = 0
        self.w("}")
        self.w()

    # -- ops ---------------------------------------------------------------

    def _op(self, op: Op) -> None:
        handler = getattr(self, f"_op_{op.opcode}", None)
        if handler is None:
            if op.opcode in BINARY:
                return self._op_binary(op)
            if op.opcode in UNARY:
                return self._op_unary(op)
            if op.opcode in REDUCTIONS:
                return self._op_reduce(op)
            if op.opcode in BROADCASTS:
                return self._op_broadcast(op)
            if op.opcode in FILLS:
                return self._op_fill(op)
            if op.opcode in MMA:
                return self._op_mma(op)
            if op.opcode.startswith("s_") and op.opcode[2:] in SCALARS:
                return self._op_scalar(op)
            raise CodegenError(
                f"no C++ emitter for IR op {op.opcode!r}"
                + (f"\n    at {op.loc}" if op.loc else "")
            )
        handler(op)

    def _dest(self, op: Op):
        """Split a writing op into (destination, sources), declaring the
        destination when the op creates one.

        Value form makes a new local; the in-place form (`out=`) writes one
        that already exists and must *not* re-declare it -- a fresh declaration
        would shadow a loop-carried accumulator and silently keep only the last
        iteration, which is exactly the class of bug this IR exists to prevent.
        """
        if op.attrs.get("inplace"):
            return op.dst, list(op.operands[1:])
        r = op.result
        self.w(f"{self.cpp(r.type)} {self.name(r)};")
        return r, list(op.operands)

    def _call(self, fn: str, dst: Value, args: Sequence[str]) -> None:
        self.w(f"kittens::{fn}({', '.join([self.name(dst), *args])});")

    # indices

    def _op_block_idx(self, op: Op) -> None:
        self.w(f"const int {self.name(op.result)} = blockIdx.{op.attrs['axis']};")

    def _op_warp_id(self, op: Op) -> None:
        # Uniform, not `warpid()`: see kittens::warpid_uniform. The IR
        # hoists this into the prologue, where every lane is active, so
        # the readfirstlane is always well defined.
        self.w(f"const int {self.name(op.result)} = kittens::warpid_uniform();")

    def _op_s_any_ne(self, op: Op) -> None:
        """A loop the compiler fully unrolls into `outer*inner` v_cmp, an or
        tree, and one `__any`. Written out rather than called because there is
        no library op for it: every other reduction in `include/rdna3` lands
        back in the register file, and this one lands in a branch."""
        a, b = (self.name(v) for v in op.operands)
        r = self.name(op.result)
        self.w(f"bool {r}_v = false;")
        self.w("#pragma unroll")
        self.w(f"for (int o = 0; o < decltype({a})::outer_dim; o++)")
        self.w("    #pragma unroll")
        self.w(f"    for (int i = 0; i < decltype({a})::inner_dim; i++)")
        self.w(f"        {r}_v |= ({a}.data[o][i] != {b}.data[o][i]);")
        self.w(f"const int {r} = __any({r}_v);")

    def _op_lane_id(self, op: Op) -> None:
        self.w(f"const int {self.name(op.result)} = kittens::laneid();")

    def _op_const(self, op: Op) -> None:
        self.w(f"const int {self.name(op.result)} = {op.attrs['value']};")

    def _op_coord(self, op: Op) -> None:
        r = op.result
        parts = ", ".join(self.name(o) for o in op.operands)
        if r.type.unit == "tile":
            # A tile coordinate has no meaning until you know which tile it is
            # in units of, and one `hk.tile_coord` can address tiles of several
            # shapes. So it is carried as a plain int4 and converted at each use
            # site via coord's int4 constructor, where the tile type is known.
            self.w(f"const int4 {self.name(r)} = make_int4({parts});")
        else:
            self.w(f"const kittens::coord<> {self.name(r)}({parts});")

    def _coord_arg(self, v: Value, tile_cpp: str) -> str:
        n = self.name(v)
        if v.type.unit == "tile":
            return f"kittens::coord<{tile_cpp}>({n})"
        return n

    # memory

    def _op_load_global(self, op: Op) -> None:
        dst, (src, idx) = self._dest(op)
        self.w(
            f"kittens::load({self.name(dst)}, {self.name(src)}, "
            f"{self._coord_arg(idx, self.cpp(dst.type))});"
        )

    def _op_store_global(self, op: Op) -> None:
        dst, val, idx = op.operands
        ty = val.type
        self.w(
            f"kittens::store({self.name(dst)}, {self.name(val)}, "
            f"{self._coord_arg(idx, self.cpp(ty))});"
        )

    def _op_alloc_shared(self, op: Op) -> None:
        r = op.result
        el = r.type.cpp()  # the entry type; the [N] goes on the declarator
        if r.type.count == 1:
            self.w(f"{el} &{self.name(r)} = al.allocate<{el}>();")
        else:
            self.w(
                f"{el} (&{self.name(r)})[{r.type.count}] = "
                f"al.allocate<{el}, {r.type.count}>();"
            )

    def _op_shared_at(self, op: Op) -> None:
        buf, idx = op.operands
        r = op.result
        self.w(
            f"{self.cpp(r.type)} &{self.name(r)} = "
            f"{self.name(buf)}[{self.name(idx)}];"
        )

    def _op_subtile(self, op: Op) -> None:
        src, row, col = op.operands
        r = op.result
        ty = r.type
        # By value, not by reference: the shared `subtile_inplace` returns a
        # fresh `st_subtile` (a pointer plus the parent's swizzle constants),
        # not a reference into anything, so `auto &` will not bind to it. The
        # copy is free and does not dangle -- st_subtile holds a raw `data`
        # pointer into LDS, which outlives every expression here. The register
        # overload of the same name *does* return a reference; if subtiling of
        # register tiles ever lands, this has to branch on the operand type.
        self.w(
            f"auto {self.name(r)} = kittens::subtile_inplace"
            f"<{ty.rows}, {ty.cols}>({self.name(src)}, "
            f"{{{self.name(row)}, {self.name(col)}}});"
        )

    def _op_setprio(self, op: Op) -> None:
        self.w(f"__builtin_amdgcn_s_setprio({op.attrs['level']});")

    # staging: the two halves of a global->LDS copy, with the bytes in VGPRs
    # in between. See hk.lang.ops.stage_buffer.

    def _op_stage_buffer(self, op: Op) -> None:
        r = op.result
        ty = r.type
        dim = f"[{ty.depth}]" if ty.depth > 1 else ""
        self.w(f"float4 {self.name(r)}{dim}[{ty.calls}];")

    def _stage_args(self, buf: Value, slot: int) -> "tuple[str, str, str]":
        """(group<W>::, buffer expression, destination template)."""
        ty = buf.type
        g = f"kittens::group<{ty.threads // 32}>::"
        expr = self.name(buf) + (f"[{slot}]" if ty.depth > 1 else "")
        tmpl = self.name(buf.producer.operands[0])
        if buf.producer.operands[0].type.count != 1:
            tmpl += "[0]"
        return g, expr, tmpl

    def _op_stage_load(self, op: Op) -> None:
        buf, src, idx = op.operands
        g, expr, tmpl = self._stage_args(buf, op.attrs["slot"])
        self.w(
            f"{g}load_global_to_register_buffer({expr}, {buf.type.calls}, "
            f"{self.name(src)}, {self._coord_arg(idx, buf.type.tile.cpp())}, "
            f"{tmpl});"
        )

    def _op_stage_commit(self, op: Op) -> None:
        dst, buf = op.operands
        g, expr, _ = self._stage_args(buf, op.attrs["slot"])
        wait = "true" if op.attrs.get("wait") else "false"
        self.w(
            f"{g}store_register_buffer_to_shared<{wait}>("
            f"{self.name(dst)}, {expr}, {buf.type.calls});"
        )

    def _op_vm_wait(self, op: Op) -> None:
        self.w(f"kittens::vm_wait<{op.attrs['keep']}>();")

    def _op_group_load(self, op: Op) -> None:
        dst, src, idx = op.operands
        g = f"kittens::group<{op.attrs['threads'] // 32}>::"
        self.w(
            f"{g}load({self.name(dst)}, {self.name(src)}, "
            f"{self._coord_arg(idx, dst.type.cpp())});"
        )

    def _op_group_store(self, op: Op) -> None:
        dst, src, idx = op.operands
        g = f"kittens::group<{op.attrs['threads'] // 32}>::"
        self.w(
            f"{g}store({self.name(dst)}, {self.name(src)}, "
            f"{self._coord_arg(idx, src.type.cpp())});"
        )

    def _op_load_shared(self, op: Op) -> None:
        dst, srcs = self._dest(op)
        (src,) = srcs
        # load<false> issues the reads and returns; the caller owes the tile an
        # lds_wait_for, which lds_pipeline has already checked it gets.
        t = "" if op.attrs.get("wait", True) else "<false>"
        self.w(f"kittens::load{t}({self.name(dst)}, {self.name(src)});")

    def _op_granules(self, op: Op) -> None:
        r = op.result
        self.w(f"{self.cpp(r.type)} {self.name(r)};")
        self.w(f"{self.name(r)}.init({self.name(op.operands[0])});")

    def _op_load_frag(self, op: Op) -> None:
        dst, srcs = self._dest(op)
        (gr,) = srcs
        # The coordinates are template arguments, which is the whole point:
        # lds_read_frag turns them into ds_read_b128's immediate offset instead
        # of into an address register.
        self.w(
            f"kittens::lds_read_frag<{16 * op.attrs['row']}, "
            f"{16 * op.attrs['col']}>({self.name(dst)}, {self.name(gr)});"
        )

    def _op_store_frag(self, op: Op) -> None:
        gr, val = op.operands[0], op.operands[1]
        row = op.attrs["row"]
        if row is None:
            # A runtime row is an addend on the granule address, pre-scaled to
            # bytes by the caller's side of lds_write_frag's contract: the row
            # term of st::idx is swizzle_bytes per row.
            sb = gr.type.swizzle_bytes
            off = f"(uint32_t)({16 * sb} * {self.name(op.operands[2])})"
            tmpl = f"<0, {16 * op.attrs['col']}>"
        else:
            off = "0u"
            tmpl = f"<{16 * row}, {16 * op.attrs['col']}>"
        self.w(
            f"kittens::lds_write_frag{tmpl}({self.name(gr)}, {off}, "
            f"{self.name(val)});"
        )

    def _op_lds_wait_for(self, op: Op) -> None:
        """s_waitcnt lgkmcnt(N), then re-bind each retired tile's registers.

        N is derived by lds_pipeline from the issue queue, never written by
        hand. The bind is not optional and not an optimization: see lds_bind in
        include/rdna3/ops/warp/memory/util/util.cuh.
        """
        n = op.attrs["n"]
        names = ", ".join(self.name(v) for v in op.operands)
        self.w(f"kittens::lds_wait_for<{n}>({names});")

    def _op_store_shared(self, op: Op) -> None:
        dst, val = op.operands
        self.w(f"kittens::store({self.name(dst)}, {self.name(val)});")

    # cross-warp

    def _op_alloc_shared_vec(self, op: Op) -> None:
        r = op.result
        el = r.type.cpp()  # the entry type; the [N] goes on the declarator
        if r.type.count == 1:
            self.w(f"{el} &{self.name(r)} = al.allocate<{el}>();")
        else:
            self.w(
                f"{el} (&{self.name(r)})[{r.type.count}] = "
                f"al.allocate<{el}, {r.type.count}>();"
            )

    def _sv_entry(self, v: Value, index: Value) -> str:
        return self.name(v) if v.type.count == 1 else f"{self.name(v)}[{self.name(index)}]"

    def _op_store_scalar(self, op: Op) -> None:
        dst, val, idx = op.operands
        self.w(
            f"kittens::store_scalar({self.name(dst)}, {self.name(val)}, "
            f"{self.name(idx)});"
        )

    def _op_store_shared_vec(self, op: Op) -> None:
        dst, val, index = op.operands
        self.w(f"kittens::store({self._sv_entry(dst, index)}, {self.name(val)});")

    def _op_load_shared_vec(self, op: Op) -> None:
        src, index = op.operands
        dst = op.result
        self.w(f"{self.cpp(dst.type)} {self.name(dst)};")
        self.w(f"kittens::load({self.name(dst)}, {self._sv_entry(src, index)});")

    def _op_barrier(self, op: Op) -> None:
        # The drain goes *before* the barrier and is a separate instruction:
        # s_barrier has no memory semantics of its own, so the lgkmcnt(0) is
        # what actually makes the LDS visible to the warps on the other side.
        if op.attrs.get("drain"):
            self.w("kittens::lds_wait<0>();")
        # The builtin, not `__syncthreads()`. They differ on gfx11: HIP lowers
        # `__syncthreads()` to the barrier *plus* a `buffer_gl0_inv`, because
        # it promises to order global memory too, and the only way to do that
        # across a workgroup is to drop the per-WGP vector L0. That is a real
        # cost in a loop -- in the GEMM it is one L0 flush per K-tile, which
        # throws away the B-tile lines the other workgroup on the WGP is about
        # to read -- and this op does not promise it. `hk.ops.barrier` is
        # documented as ordering execution and not memory; `lds_pipeline`
        # separately proves the LDS side, either by finding a wait that already
        # retired the queue or by making the author write `drain=True`. A
        # kernel that genuinely needs cross-workgroup *global* ordering needs a
        # fence op of its own, which would be honest about costing an L0 flush.
        self.w("__builtin_amdgcn_s_barrier();")

    def _op_retype_vec(self, op: Op) -> None:
        (src,) = op.operands
        r = op.result
        a, b = self.cpp(r.type), self.cpp(src.type)
        # The trace-time check in lang.ops.as_vec already established that
        # these name the same rv<T, length, layout>. Restating it here means a
        # future change to rt.cuh's col_vec alias is a compile error on this
        # line, and not a vector that silently reduces the wrong lanes.
        self.w(
            f'static_assert(std::is_same_v<{a}, {b}>, "hk: as_vec between '
            f'distinct rv types");'
        )
        self.w(f"{a} &{self.name(r)} = {self.name(src)};")

    # creation

    def _op_zero(self, op: Op) -> None:
        r, _ = self._dest(op)
        self.w(f"kittens::zero({self.name(r)});")

    @staticmethod
    def _float_lit(v: float) -> str:
        """Python's repr of an infinity is `inf`, which is not a C++ token.

        Worth a helper rather than a special case at each site: -inf is the
        identity for max and turns up wherever a reduction is seeded or an
        out-of-bounds lane is masked, and `(float)-inf` compiles to an
        undeclared-identifier error a long way from the line that wrote it.
        """
        if v != v:
            return "NAN"
        if v == float("inf"):
            return "INFINITY"
        if v == float("-inf"):
            return "-INFINITY"
        return repr(float(v))

    def _op_full(self, op: Op) -> None:
        r, _ = self._dest(op)
        n = self.name(r)
        v = op.attrs["value"]
        if v == 0:
            self.w(f"kittens::zero({n});")
        elif v == 1:
            self.w(f"kittens::one({n});")
        elif v == float("-inf"):
            self.w(f"kittens::neg_infty({n});")
        elif v == float("inf"):
            self.w(f"kittens::pos_infty({n});")
        else:
            # There is no fill-with-a-constant in maps.cuh; zero then add folds
            # to the same VALU sequence.
            self.w(f"kittens::zero({n});")
            self.w(f"kittens::add({n}, {n}, ({r.type.dtype.cpp}){self._float_lit(v)});")

    def _op_neg_infty(self, op: Op) -> None:
        r, _ = self._dest(op)
        self.w(f"kittens::neg_infty({self.name(r)});")

    # maps

    def _op_binary(self, op: Op) -> None:
        fn = BINARY[op.opcode].cpp
        dst, src = self._dest(op)
        args = [self.name(s) for s in src]
        if op.attrs.get("scalar_rhs"):
            # The last operand is a device scalar, not a tile: cast it to the
            # element type so the map's templated right operand resolves the
            # same way it does for a literal.
            args[-1] = f"({dst.type.dtype.cpp}){args[-1]}"
        if "scalar" in op.attrs:
            args.append(f"({dst.type.dtype.cpp}){self._float_lit(op.attrs['scalar'])}")
        self._call(fn, dst, args)

    def _op_unary(self, op: Op) -> None:
        dst, src = self._dest(op)
        self._call(UNARY[op.opcode].cpp, dst, [self.name(s) for s in src])

    def _op_mma(self, op: Op) -> None:
        """kittens::mma_X(d, a, b, c).

        Destination-passing like everything else, and the in-place form passes
        the accumulator as both d and c -- which is what the GEMM inner loop
        wants and what `out=acc` means. Nothing is re-declared there; see
        _dest.
        """
        dst, srcs = self._dest(op)
        self._call(op.opcode, dst, [self.name(v) for v in srcs])

    def _op_cast(self, op: Op) -> None:
        dst, src = self._dest(op)
        self._call("copy", dst, [self.name(s) for s in src])

    # reductions and broadcasts

    def _op_reduce(self, op: Op) -> None:
        dst, src = self._dest(op)
        args = [self.name(s) for s in src]
        if op.attrs.get("accumulate"):
            # The three-argument overload: read the accumulator, fold the tile
            # into it, write it back. Without this the loop form would restart
            # the reduction on every iteration.
            args.append(self.name(dst))
        self._call(op.opcode, dst, args)

    def _op_broadcast(self, op: Op) -> None:
        dst, src = self._dest(op)
        self._call(op.opcode, dst, [self.name(s) for s in src])

    def _op_broadcast_row(self, op: Op) -> None:
        dst, src = self._dest(op)
        self._call("broadcast_row", dst, [self.name(s) for s in src])

    def _op_broadcast_col(self, op: Op) -> None:
        dst, src = self._dest(op)
        self._call("broadcast_col", dst, [self.name(s) for s in src])

    def _op_fill(self, op: Op) -> None:
        dst, src = self._dest(op)
        args = [self.name(s) for s in src]
        args.append(f"({dst.type.dtype.cpp}){self._float_lit(op.attrs['value'])}")
        self._call(op.opcode, dst, args)

    # transpose and masking

    def _op_transpose(self, op: Op) -> None:
        dst, src = self._dest(op)
        self._call("transpose", dst, [self.name(s) for s in src])

    def _op_transpose_sep(self, op: Op) -> None:
        dst, src = self._dest(op)
        self._call("transpose_sep", dst, [self.name(s) for s in src])

    def _op_make_causal(self, op: Op) -> None:
        self._causal("make_causal", op)

    def _op_make_causal_t(self, op: Op) -> None:
        self._causal("make_causal_t", op)

    def _causal(self, fn: str, op: Op) -> None:
        dst, src = self._dest(op)
        args = [self.name(s) for s in src]
        # The fill value is the *unpacked* element type, not the tile's packed
        # one -- `base_types::packing<T>::unpacked_type` in the signature. For
        # fp32 those coincide; for bf16 the tile's `dtype.cpp` is the packed
        # pair and casting to it here would be a compile error naming a
        # template. So no cast at all: the literal converts implicitly, which
        # is what the library's own `val=0` default does.
        args.append(self._float_lit(op.attrs["value"]))
        self._call(fn, dst, args)

    # scalar arithmetic
    #
    # Written out as expressions rather than routed through ::min / ::cdiv:
    # these are a handful of characters either way, and an expression the
    # reader can check by eye beats a name they have to go look up. Operands
    # are always `const int` locals, so naming one twice costs nothing.
    _SCALAR_EXPR = {
        "add": "{a} + {b}",
        "sub": "{a} - {b}",
        "mul": "{a} * {b}",
        "div": "{a} / {b}",
        "mod": "{a} % {b}",
        "min": "({a} < {b}) ? {a} : {b}",
        "max": "({a} > {b}) ? {a} : {b}",
        "cdiv": "({a} + {b} - 1) / {b}",
        "lt": "{a} < {b}", "le": "{a} <= {b}", "gt": "{a} > {b}",
        "ge": "{a} >= {b}", "eq": "{a} == {b}", "ne": "{a} != {b}",
    }

    def _op_scalar(self, op: Op) -> None:
        a, b = (self.name(o) for o in op.operands)
        expr = self._SCALAR_EXPR[op.opcode[2:]].format(a=a, b=b)
        self.w(f"const int {self.name(op.result)} = {expr};")

    def _op_extent(self, op: Op) -> None:
        (t,) = op.operands
        axis = op.attrs["axis"]
        self.w(f"const int {self.name(op.result)} = {self.name(t)}.{axis}();")

    # control flow

    def _op_if(self, op: Op) -> None:
        (cond,) = op.operands
        c = self.name(cond)
        if op.attrs.get("opaque"):
            # The condition is `const int` everywhere else, and an "+v" operand
            # has to be writable, so the opaque form needs a copy to hand the
            # optimizer something it cannot see through.
            self._opaque += 1
            c = f"{c}_live{self._opaque}"
            self.w(f"int {c} = {self.name(cond)};")
            self.w(f'asm volatile("" : "+v"({c}));')
        self.w(f"if ({c}) {{")
        self.indent += 1
        for inner in op.body:
            self._op(inner)
        self.indent -= 1
        self.w("}")

    def _op_sched_barrier(self, op: Op) -> None:
        self.w("__builtin_amdgcn_sched_barrier(0);")

    def _op_for(self, op: Op) -> None:
        (bound,) = op.operands
        (iv,) = op.block_args
        n = self.name(iv)
        unroll = op.attrs.get("unroll", 1)
        if unroll > 1:
            self.w(f"#pragma unroll {unroll}")
        self.w(f"for (int {n} = 0; {n} < {self.name(bound)}; ++{n}) {{")
        self.indent += 1
        for inner in op.body:
            self._op(inner)
        self.indent -= 1
        self.w("}")


def emit(ir: KernelIR, includes: Sequence[str] = ('"kittens.cuh"',)) -> str:
    return Emitter(ir).emit(includes)
