"""HK IR -> HipKittens C++.

The output is meant to be *read*. When a kernel spills or mis-schedules, the
generated .cpp is the artifact you take to /kernel-resource-check and to the
disassembler, and a generator whose output nobody can follow just moves the
debugging problem somewhere worse. So: real names, the IR op that produced each
line in a comment, and the same structure a hand-written kernel in
kernels/rdna3 has (globals struct, config, __global__, launch, pybind).

Values become named C++ locals and every op is emitted in destination-passing
form, which is what include/rdna3 exposes. The IR is in value form precisely so
that this step -- and only this step -- has to think about destinations.
"""

from __future__ import annotations

from typing import Dict, List, Sequence

from ..ir.nodes import (
    GlobalType,
    KernelIR,
    Op,
    RegTileType,
    RegVecType,
    SharedTileType,
    Value,
)
from ..lang.host import emit_dim
from ..lang.ops import (BINARY, BROADCASTS, FILLS, MMA, REDUCTIONS, SCALARS,
                        UNARY)
from ..target import get_target


class CodegenError(Exception):
    pass


class Emitter:
    def __init__(self, ir: KernelIR):
        self.ir = ir
        self.target = get_target(ir.arch)
        # Shared with ir.dump(), so the textual IR and the C++ name each value
        # identically.
        self.names: Dict[int, str] = ir.value_names()
        self.aliases: Dict[object, str] = {}
        self.lines: List[str] = []
        self.indent = 1

    # -- helpers -----------------------------------------------------------

    def w(self, line: str = "") -> None:
        self.lines.append(("    " * self.indent + line) if line else "")

    def name(self, v: Value) -> str:
        # A tensor is a member of the globals struct, not a local.
        if isinstance(v.type, GlobalType):
            return f"g.{v.name}"
        n = self.names.get(id(v))
        if n is None:
            raise CodegenError(
                f"value {v!r} ({v.type}) has no definition in this kernel. "
                f"It was most likely produced while tracing a different kernel."
            )
        return n

    # -- top level ---------------------------------------------------------

    def emit(self, includes: Sequence[str] = ('"kittens.cuh"',)) -> str:
        """Everything except the module scaffold: includes, globals, the
        __global__ itself and a host `launch`. What wraps it -- pybind, a torch
        library, nothing at all -- is codegen.scaffold's business."""
        self.lines = []
        self._header(includes)
        self._globals_struct()
        self._kernel()
        self._launch()
        return "\n".join(self.lines) + "\n"

    def _header(self, includes: Sequence[str]) -> None:
        ir = self.ir
        self.indent = 0
        self.w("// Generated by hk (HipKittens Python IR). Do not edit by hand;")
        self.w("// edit the kernel that produced it and regenerate.")
        self.w("//")
        self.w(f"// kernel : {ir.name}")
        self.w(f"// arch   : {ir.arch}  warps={ir.warps} threads={ir.threads}")
        if ir.consts:
            consts = ", ".join(f"{k}={v}" for k, v in sorted(ir.consts.items()))
            self.w(f"// const  : {consts}")
        self.w(f"// LDS    : {ir.lds_bytes} B")
        for wn in ir.warnings:
            for line in str(wn).splitlines():
                self.w(f"// WARN   : {line.strip()}")
        self.w()
        for inc in includes:
            self.w(f"#include {inc}")
        self.w()
        self.w("using namespace kittens;")
        self.w()

    def _globals_struct(self) -> None:
        ir = self.ir
        self.w("struct globals {")
        self.indent = 1
        for p in ir.tensors():
            self.w(f"{p.type.cpp()} {p.name};")
        self.w()
        self.w("dim3 grid() const {")
        self.indent = 2
        # `g` is the name the host expressions were built against.
        self.w("const globals &g = *this;")
        x, y, z = ir.grid
        self.w(f"return dim3({emit_dim(x)}, {emit_dim(y)}, {emit_dim(z)});")
        self.indent = 1
        self.w("}")
        self.w(f"dim3 block() const {{ return dim3({ir.threads}); }}")
        if ir.lds_bytes:
            self.w(f"size_t dynamic_shared_memory() const {{ return {ir.lds_bytes}; }}")
        self.indent = 0
        self.w("};")
        self.w()

    def _aliases(self) -> None:
        """One `using` per distinct tile or vector type.

        Spelled out, `kittens::rt<bf16, 16, 64, kittens::ducks::rt_layout::row>`
        is 55 characters that appear on nearly every line, and the attention
        kernel has six such types. Aliasing them is the difference between
        generated code you can diff against the hand-written kernel and
        generated code you skim past.

        Vectors get an alias too, and it is spelled in terms of the tile's --
        `rt_fp32_16x64_row::col_vec` -- because that is the only honest way to
        write it: an rv's lane layout is derived from the tile it came off, and
        a vector written independently of its tile is the bug this naming makes
        hard to commit.
        """
        seen = {}

        def note(ty) -> None:
            # `.plain`: a refinement the IR tracks (RegVecType.uniform) has no
            # C++ spelling, so the refined and the plain vector are one alias.
            ty = ty.plain
            if isinstance(ty, RegVecType):
                note(ty.tile)  # before the vector, so the `using` order works
            if isinstance(ty, (RegTileType, SharedTileType, RegVecType)):
                seen.setdefault(ty, self._alias_name(ty))

        for op in self.ir.walk():
            for v in list(op.results) + list(op.operands) + list(op.block_args):
                note(v.type)
        if not seen:
            return
        for ty, alias in seen.items():
            if isinstance(ty, RegVecType):
                self.w(f"using {alias} = {seen[ty.tile]}::{ty.kind}_vec;")
            else:
                self.w(f"using {alias} = {ty.cpp()};")
        self.w()
        self.aliases = {ty: alias for ty, alias in seen.items()}

    @staticmethod
    def _alias_name(ty) -> str:
        if isinstance(ty, RegTileType):
            return f"rt_{ty.dtype.name}_{ty.rows}x{ty.cols}_{ty.layout}"
        if isinstance(ty, RegVecType):
            t = ty.tile
            return f"rv_{t.dtype.name}_{t.rows}x{t.cols}_{t.layout}_{ty.kind}"
        return f"st_{ty.dtype.name}_{ty.rows}x{ty.cols}"

    def cpp(self, ty) -> str:
        """The name to write for a type: its alias when it has one."""
        return self.aliases.get(ty.plain, None) or ty.cpp()

    def _kernel(self) -> None:
        ir = self.ir
        self._aliases()
        self.w(f"__global__ __launch_bounds__({ir.threads}, 1)")
        self.w(f"void {ir.name}_kernel(const globals g) {{")
        self.indent = 1
        if ir.lds_bytes:
            self.w("extern __shared__ alignment_dummy __shm[];")
            self.w("shared_allocator al((int*)&__shm[0]);")
            self.w()
        for op in ir.body:
            self._op(op)
        self.indent = 0
        self.w("}")
        self.w()

    def _launch(self) -> None:
        ir = self.ir
        self.w("static void launch(const globals &g) {")
        self.indent = 1
        if ir.lds_bytes:
            self.w(
                f"hipFuncSetAttribute((void *)&{ir.name}_kernel, "
                f"hipFuncAttributeMaxDynamicSharedMemorySize, {ir.lds_bytes});"
            )
            self.w(f"{ir.name}_kernel<<<g.grid(), g.block(), {ir.lds_bytes}>>>(g);")
        else:
            self.w(f"{ir.name}_kernel<<<g.grid(), g.block()>>>(g);")
        self.indent = 0
        self.w("}")
        self.w()

    # -- ops ---------------------------------------------------------------

    def _op(self, op: Op) -> None:
        handler = getattr(self, f"_op_{op.opcode}", None)
        if handler is None:
            if op.opcode in BINARY:
                return self._op_binary(op)
            if op.opcode in UNARY:
                return self._op_unary(op)
            if op.opcode in REDUCTIONS:
                return self._op_reduce(op)
            if op.opcode in BROADCASTS:
                return self._op_broadcast(op)
            if op.opcode in FILLS:
                return self._op_fill(op)
            if op.opcode in MMA:
                return self._op_mma(op)
            if op.opcode.startswith("s_") and op.opcode[2:] in SCALARS:
                return self._op_scalar(op)
            raise CodegenError(
                f"no C++ emitter for IR op {op.opcode!r}"
                + (f"\n    at {op.loc}" if op.loc else "")
            )
        handler(op)

    def _dest(self, op: Op):
        """Split a writing op into (destination, sources), declaring the
        destination when the op creates one.

        Value form makes a new local; the in-place form (`out=`) writes one
        that already exists and must *not* re-declare it -- a fresh declaration
        would shadow a loop-carried accumulator and silently keep only the last
        iteration, which is exactly the class of bug this IR exists to prevent.
        """
        if op.attrs.get("inplace"):
            return op.dst, list(op.operands[1:])
        r = op.result
        self.w(f"{self.cpp(r.type)} {self.name(r)};")
        return r, list(op.operands)

    def _call(self, fn: str, dst: Value, args: Sequence[str]) -> None:
        self.w(f"kittens::{fn}({', '.join([self.name(dst), *args])});")

    # indices

    def _op_block_idx(self, op: Op) -> None:
        self.w(f"const int {self.name(op.result)} = blockIdx.{op.attrs['axis']};")

    def _op_warp_id(self, op: Op) -> None:
        self.w(f"const int {self.name(op.result)} = kittens::warpid();")

    def _op_lane_id(self, op: Op) -> None:
        self.w(f"const int {self.name(op.result)} = kittens::laneid();")

    def _op_const(self, op: Op) -> None:
        self.w(f"const int {self.name(op.result)} = {op.attrs['value']};")

    def _op_coord(self, op: Op) -> None:
        r = op.result
        parts = ", ".join(self.name(o) for o in op.operands)
        if r.type.unit == "tile":
            # A tile coordinate has no meaning until you know which tile it is
            # in units of, and one `hk.tile_coord` can address tiles of several
            # shapes. So it is carried as a plain int4 and converted at each use
            # site via coord's int4 constructor, where the tile type is known.
            self.w(f"const int4 {self.name(r)} = make_int4({parts});")
        else:
            self.w(f"const kittens::coord<> {self.name(r)}({parts});")

    def _coord_arg(self, v: Value, tile_cpp: str) -> str:
        n = self.name(v)
        if v.type.unit == "tile":
            return f"kittens::coord<{tile_cpp}>({n})"
        return n

    # memory

    def _op_load_global(self, op: Op) -> None:
        src, idx = op.operands
        dst = op.result
        ty = dst.type
        self.w(f"{self.cpp(ty)} {self.name(dst)};")
        self.w(
            f"kittens::load({self.name(dst)}, {self.name(src)}, "
            f"{self._coord_arg(idx, self.cpp(ty))});"
        )

    def _op_store_global(self, op: Op) -> None:
        dst, val, idx = op.operands
        ty = val.type
        self.w(
            f"kittens::store({self.name(dst)}, {self.name(val)}, "
            f"{self._coord_arg(idx, self.cpp(ty))});"
        )

    def _op_alloc_shared(self, op: Op) -> None:
        r = op.result
        self.w(f"{self.cpp(r.type)} &{self.name(r)} = al.allocate<{self.cpp(r.type)}>();")

    def _op_load_shared(self, op: Op) -> None:
        dst, srcs = self._dest(op)
        (src,) = srcs
        # load<false> issues the reads and returns; the caller owes the tile an
        # lds_wait_for, which lds_pipeline has already checked it gets.
        t = "" if op.attrs.get("wait", True) else "<false>"
        self.w(f"kittens::load{t}({self.name(dst)}, {self.name(src)});")

    def _op_lds_wait_for(self, op: Op) -> None:
        """s_waitcnt lgkmcnt(N), then re-bind each retired tile's registers.

        N is derived by lds_pipeline from the issue queue, never written by
        hand. The bind is not optional and not an optimization: see lds_bind in
        include/rdna3/ops/warp/memory/util/util.cuh.
        """
        n = op.attrs["n"]
        names = ", ".join(self.name(v) for v in op.operands)
        self.w(f"kittens::lds_wait_for<{n}>({names});")

    def _op_store_shared(self, op: Op) -> None:
        dst, val = op.operands
        self.w(f"kittens::store({self.name(dst)}, {self.name(val)});")

    # cross-warp

    def _op_alloc_shared_vec(self, op: Op) -> None:
        r = op.result
        el = r.type.cpp()  # the entry type; the [N] goes on the declarator
        if r.type.count == 1:
            self.w(f"{el} &{self.name(r)} = al.allocate<{el}>();")
        else:
            self.w(
                f"{el} (&{self.name(r)})[{r.type.count}] = "
                f"al.allocate<{el}, {r.type.count}>();"
            )

    def _sv_entry(self, v: Value, index: Value) -> str:
        return self.name(v) if v.type.count == 1 else f"{self.name(v)}[{self.name(index)}]"

    def _op_store_scalar(self, op: Op) -> None:
        dst, val, idx = op.operands
        self.w(
            f"kittens::store_scalar({self.name(dst)}, {self.name(val)}, "
            f"{self.name(idx)});"
        )

    def _op_store_shared_vec(self, op: Op) -> None:
        dst, val, index = op.operands
        self.w(f"kittens::store({self._sv_entry(dst, index)}, {self.name(val)});")

    def _op_load_shared_vec(self, op: Op) -> None:
        src, index = op.operands
        dst = op.result
        self.w(f"{self.cpp(dst.type)} {self.name(dst)};")
        self.w(f"kittens::load({self.name(dst)}, {self._sv_entry(src, index)});")

    def _op_barrier(self, op: Op) -> None:
        self.w("__syncthreads();")

    def _op_retype_vec(self, op: Op) -> None:
        (src,) = op.operands
        r = op.result
        a, b = self.cpp(r.type), self.cpp(src.type)
        # The trace-time check in lang.ops.as_vec already established that
        # these name the same rv<T, length, layout>. Restating it here means a
        # future change to rt.cuh's col_vec alias is a compile error on this
        # line, and not a vector that silently reduces the wrong lanes.
        self.w(
            f'static_assert(std::is_same_v<{a}, {b}>, "hk: as_vec between '
            f'distinct rv types");'
        )
        self.w(f"{a} &{self.name(r)} = {self.name(src)};")

    # creation

    def _op_zero(self, op: Op) -> None:
        r = op.result
        self.w(f"{self.cpp(r.type)} {self.name(r)};")
        self.w(f"kittens::zero({self.name(r)});")

    @staticmethod
    def _float_lit(v: float) -> str:
        """Python's repr of an infinity is `inf`, which is not a C++ token.

        Worth a helper rather than a special case at each site: -inf is the
        identity for max and turns up wherever a reduction is seeded or an
        out-of-bounds lane is masked, and `(float)-inf` compiles to an
        undeclared-identifier error a long way from the line that wrote it.
        """
        if v != v:
            return "NAN"
        if v == float("inf"):
            return "INFINITY"
        if v == float("-inf"):
            return "-INFINITY"
        return repr(float(v))

    def _op_full(self, op: Op) -> None:
        r = op.result
        n = self.name(r)
        v = op.attrs["value"]
        self.w(f"{self.cpp(r.type)} {n};")
        if v == 0:
            self.w(f"kittens::zero({n});")
        elif v == 1:
            self.w(f"kittens::one({n});")
        elif v == float("-inf"):
            self.w(f"kittens::neg_infty({n});")
        elif v == float("inf"):
            self.w(f"kittens::pos_infty({n});")
        else:
            # There is no fill-with-a-constant in maps.cuh; zero then add folds
            # to the same VALU sequence.
            self.w(f"kittens::zero({n});")
            self.w(f"kittens::add({n}, {n}, ({r.type.dtype.cpp}){self._float_lit(v)});")

    def _op_neg_infty(self, op: Op) -> None:
        r = op.result
        self.w(f"{self.cpp(r.type)} {self.name(r)};")
        self.w(f"kittens::neg_infty({self.name(r)});")

    # maps

    def _op_binary(self, op: Op) -> None:
        fn = BINARY[op.opcode].cpp
        dst, src = self._dest(op)
        args = [self.name(s) for s in src]
        if op.attrs.get("scalar_rhs"):
            # The last operand is a device scalar, not a tile: cast it to the
            # element type so the map's templated right operand resolves the
            # same way it does for a literal.
            args[-1] = f"({dst.type.dtype.cpp}){args[-1]}"
        if "scalar" in op.attrs:
            args.append(f"({dst.type.dtype.cpp}){self._float_lit(op.attrs['scalar'])}")
        self._call(fn, dst, args)

    def _op_unary(self, op: Op) -> None:
        dst, src = self._dest(op)
        self._call(UNARY[op.opcode].cpp, dst, [self.name(s) for s in src])

    def _op_mma(self, op: Op) -> None:
        """kittens::mma_X(d, a, b, c).

        Destination-passing like everything else, and the in-place form passes
        the accumulator as both d and c -- which is what the GEMM inner loop
        wants and what `out=acc` means. Nothing is re-declared there; see
        _dest.
        """
        dst, srcs = self._dest(op)
        self._call(op.opcode, dst, [self.name(v) for v in srcs])

    def _op_cast(self, op: Op) -> None:
        dst, src = self._dest(op)
        self._call("copy", dst, [self.name(s) for s in src])

    # reductions and broadcasts

    def _op_reduce(self, op: Op) -> None:
        dst, src = self._dest(op)
        args = [self.name(s) for s in src]
        if op.attrs.get("accumulate"):
            # The three-argument overload: read the accumulator, fold the tile
            # into it, write it back. Without this the loop form would restart
            # the reduction on every iteration.
            args.append(self.name(dst))
        self._call(op.opcode, dst, args)

    def _op_broadcast(self, op: Op) -> None:
        dst, src = self._dest(op)
        self._call(op.opcode, dst, [self.name(s) for s in src])

    def _op_broadcast_row(self, op: Op) -> None:
        dst, src = self._dest(op)
        self._call("broadcast_row", dst, [self.name(s) for s in src])

    def _op_broadcast_col(self, op: Op) -> None:
        dst, src = self._dest(op)
        self._call("broadcast_col", dst, [self.name(s) for s in src])

    def _op_fill(self, op: Op) -> None:
        dst, src = self._dest(op)
        args = [self.name(s) for s in src]
        args.append(f"({dst.type.dtype.cpp}){self._float_lit(op.attrs['value'])}")
        self._call(op.opcode, dst, args)

    # scalar arithmetic
    #
    # Written out as expressions rather than routed through ::min / ::cdiv:
    # these are a handful of characters either way, and an expression the
    # reader can check by eye beats a name they have to go look up. Operands
    # are always `const int` locals, so naming one twice costs nothing.
    _SCALAR_EXPR = {
        "add": "{a} + {b}",
        "sub": "{a} - {b}",
        "mul": "{a} * {b}",
        "div": "{a} / {b}",
        "mod": "{a} % {b}",
        "min": "({a} < {b}) ? {a} : {b}",
        "max": "({a} > {b}) ? {a} : {b}",
        "cdiv": "({a} + {b} - 1) / {b}",
    }

    def _op_scalar(self, op: Op) -> None:
        a, b = (self.name(o) for o in op.operands)
        expr = self._SCALAR_EXPR[op.opcode[2:]].format(a=a, b=b)
        self.w(f"const int {self.name(op.result)} = {expr};")

    def _op_extent(self, op: Op) -> None:
        (t,) = op.operands
        axis = op.attrs["axis"]
        self.w(f"const int {self.name(op.result)} = {self.name(t)}.{axis}();")

    # control flow

    def _op_for(self, op: Op) -> None:
        (bound,) = op.operands
        (iv,) = op.block_args
        n = self.name(iv)
        unroll = op.attrs.get("unroll", 1)
        if unroll > 1:
            self.w(f"#pragma unroll {unroll}")
        self.w(f"for (int {n} = 0; {n} < {self.name(bound)}; ++{n}) {{")
        self.indent += 1
        for inner in op.body:
            self._op(inner)
        self.indent -= 1
        self.w("}")


def emit(ir: KernelIR, includes: Sequence[str] = ('"kittens.cuh"',)) -> str:
    return Emitter(ir).emit(includes)
